Update portmaster

diff --git a/jails/portmaster b/jails/portmaster
--- a/jails/portmaster
+++ b/jails/portmaster
@@ -1,30 +1,39 @@
 #!/bin/sh
-readlink_cmd="/usr/bin/readlink"
+basename_cmd="/usr/bin/basename"
 dirname_cmd="/usr/bin/dirname"
+readlink_cmd="/usr/bin/readlink"
 command_rc="command.rc"
+
+# Absolute path to this script, e.g. /home/user/bin/foo.csh
+SCRIPT=`${readlink_cmd} -f "$0"`
+SCRIPT_NAME=`${basename_cmd} "${SCRIPT}"`
+# Absolute path this script is in, thus /home/user/bin
+SCRIPT_PATH=`${dirname_cmd} "${SCRIPT}"`
 
 unset BYPASS
 unset FORCE
-while getopts 'fy' c
+while getopts 'fyh' c
 do
 	case $c in
 		y) BYPASS="-y " ;;
 		f) FORCE=" --no-confirm" ;;
+		h)
+			echo "usage: ${SCRIPT_NAME} [-fhy]"
+			echo "  -f   Do not confirm to update the ports inside the jail."
+			echo "  -h   This help."
+			echo "  -y   Run the command on all jails without asking."
+			exit 0
+			;;
 	esac
 done
 shift $((OPTIND-1))
-
-# Absolute path to this script, e.g. /home/user/bin/foo.csh
-SCRIPT=`${readlink_cmd} -f "$0"`
-# Absolute path this script is in, thus /home/user/bin
-SCRIPT_PATH=`${dirname_cmd} "$SCRIPT"`
 
 if [ -e "${SCRIPT_PATH}/${command_rc}" ]
 then
 	COMMAND="/usr/local/sbin/portmaster -a${FORCE}"
 	(${SCRIPT_PATH}/${command_rc} ${BYPASS}${COMMAND})
-else
-	echo "Internal script fail."
+	exit $?
 fi
 
-exit $?
+echo "Internal script failure."
+exit 1
